[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
